### СЦЕНАРИЙ 1: Регистрация нового пользователя (Например, Администратор или Покупатель)
# Важно: Убедись, что в твоей таблице Roles есть запись с RoleId = 1 (например, Admin)
POST http://localhost:5008/api/users/register
Content-Type: application/json

{
  "email": "yana_developer@milka.com",
  "password": "securePass777",
  "firstName": "Яна",
  "lastName": "Лид",
  "phone": "+79998887766",
  "roleId": 1
}

###

### СЦЕНАРИЙ 2: Успешный Вход (Login)
POST http://localhost:5008/api/users/login
Content-Type: application/json

{
  "email": "yana_developer@milka.com",
  "password": "securePass777"
}

###

### СЦЕНАРИЙ 3: Ошибка входа (Неверный пароль)
POST http://localhost:5008/api/users/login
Content-Type: application/json

{
  "email": "yana_developer@milka.com",
  "password": "wrongPasswordHere"
}
### 1. Проверка фильтра по категории (должно вернуть наше худи)
GET http://localhost:5008/api/products?category=Худи и Свитшоты

### 2. Проверка пустой категории (должно вернуть пустой список [], так как штанов мы еще не добавляли)
GET http://localhost:5008/api/products?category=Штаны и Джинсы

### 3. Фильтр по размеру (вернет худи, так как размеры S и M у нас есть на складе)
GET http://localhost:5008/api/products?size=M

### 4. Фильтр по цвету и размеру одновременно (Угольно-Чёрный в размере M у нас есть!)
GET http://localhost:5008/api/products?color=Угольно-Чёрный&size=M